[workspace]
resolver = "2"
members = [
    "mc-network",
    "mc-tick",
    "mc-proc",
    "mc-example",
    "mc-loader",
    "mclib-protocol",
    "tcp-test",
    "mc-status",
    "mc-registry",
]

[profile.release]
debug = true
