[package]
name = "mclib-network"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib"]

[dependencies]
pluggie = { path = "../../pluggie/pluggie" }
mclib-protocol = { path = "../mclib-protocol" }
