[package]
name = "mclib-protocol"
version = "0.1.0"
edition = "2024"

[features]
serde = ["dep:serde", "mc-proc/serde-derive"]

[dependencies]
mc-proc = { path = "../mc-proc" }
serde = { version = "1.0", features = ["derive"], optional = true }
