[package]
name = "mc-proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
serde-derive = []

[dependencies]
heck = "0.5"
proc-macro-error2 = "2.0.1"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
